apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-react
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: react-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: react-container
          image: my-pod-react
  
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: frontend