apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-react
  labels:
    app: myapp
    type: frontend

spec:
  selector:
    name: myapp
  template:
    metadata:
      name: react-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: react-container
          image: pod-react:release0
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: frontend

