apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  restartPolicy: Always
  containers:
    - name: my-nginx
      image: nginx:alpine
      command: ["/bin/sh","-c"]
      args: ["nginx && wget localhost:80"]