version: '3'

services:
  redis: 
    image: redis  
    command: "redis-server"
    networks:
      - api_network
    ports:
    - "6379:6379"
  api:
    
    build:
      dockerfile: Dockerfile
      context: ./backend
    networks:
      - api_network
    environment:
      PORT: 5000
      REDIS_HOST: "compose_redis_1"
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
  
networks:
  api_network:

    