version: '3'

services:
  redis: 
    image: redis
    environment:
    - REDIS_HOST=redis
    ports:
    - "6379:6379"
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PGPORT=5000
    ports:
      - "5000:5000"
  
    