apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    app: my-pg
    type: db

spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        app: my-pg
        type: db

    spec: 
      containers:
        - name: pg-container
          image: postgres:alpine
          env: 
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password-secret
                  key: PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: configMap
                  key: PG_USER
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: configMap
                  key: PG_DB
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: configMap
                  key: PG_PORT
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: configMap
                  key: PG_HOST

  replicas: 1
  selector:
    matchLabels:
      app: my-pg
      type: db 