version: '3'

services:
  redis: 
    image: redis  
    command: "redis-server"
    networks:
      - api_network
    ports:
    - "6379:6379"
  api:
    
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - "C:/Users/qodsp/Desktop/Studia/semestr 4/Technologie_Chmurowe/mwiecaszek-Technologie-Chumorwe/lab_07/compose/backend:/app/backend"
    networks:
      - api_network
    environment:
      PORT: 5000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
  
networks:
  api_network:

    